hash-format = "sha256"

[[files]]
file = "README.md"
hash = "36a30899608ef9fe6e4e0c64fa8d52233b2ac19a85c1030668bd6e3706498685"

[[files]]
file = "instance.cfg"
hash = "ed5509b6cac65bd09eb2618445739ee092850c6f0afe987d2efbde8cbe496a63"

[[files]]
file = "mods/ae2.pw.toml"
hash = "74bbdad7434bc02ec767c15c0136269f885331601f73fa2365252c24e58c09bd"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "e1016eb125a5a41a10f80847eb00affae0e539e703846f303949ed5d82b7f1bf"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "416c089224a401ec7c0ef60ae6f1f8555e783f89ec6aba49d72f41c58d7955d2"
metafile = true

[[files]]
file = "mods/am-override.pw.toml"
hash = "05f977924e514a76169d82b49b0d5e8fd8e19cca56a1eb0354ead5c75a87fcbc"
metafile = true

[[files]]
file = "mods/apotheosis.pw.toml"
hash = "c281ef574be46e4df3f7ed04b0a4b5f6d1b2a836b7d1d94c4a30be9c85d3adcb"
metafile = true

[[files]]
file = "mods/apotheotic-creation-6.0.pw.toml"
hash = "43e9fe92a073d5e2163a0233a608e1d518c1e90828a5b9687e17fde848bf1bf5"
metafile = true

[[files]]
file = "mods/apothic-attributes.pw.toml"
hash = "5f3996f32795f87086cd2e34ac1d7cc281411fe0c8799cb589706680107171ee"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "705856841852ca6823fb2b16c7e82c15ce251bf995ac6ac725ee5665d3b54dd1"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "e11ddca37c00c8cdf8ee89c7b59df544f50966d2d6c5b016916f023afb98c02e"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "258431b158c3adc8e7bf4ac8ea9cec20def2e3c373294488d72c238bcbd7538a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "fec49033058ced91f7668d4e305e599f5527501ef37c1f30f96d8927d6202d32"
metafile = true

[[files]]
file = "mods/better-f3.pw.toml"
hash = "399ed5a767b6a87c86d04a7d915035a413dc973e1f84414134af6f65bdc6ff9f"
metafile = true

[[files]]
file = "mods/better-farming-plus.pw.toml"
hash = "a8d1463905877b52b0ee7ce58ebac60e2731dca5230e3dde5cb79fa4308cfac1"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "2bcea8e16d358942a8f8b8cf6e39cc303d90fac29b1b3ecb8033bd214d4afa0f"
metafile = true

[[files]]
file = "mods/blood-magic.pw.toml"
hash = "34021b5e1c4725156f1d864fc637efb43dfb96ee473c65716982fb0bcd3c1223"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "02062a6b61e230e7debaf1c03d5e1e7203e427588fceb9f3d6ef8cad8062397e"
metafile = true

[[files]]
file = "mods/caelum.pw.toml"
hash = "33735d57abe99591ac312f8a307e539bbc45ede5df0292f992c7e62d7ca23541"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "14481081a9e233f4ba57df8a77ce028184818143eae1c73b60749ea482c912e9"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "c45dce6b9e52796c0606ff222efa5833fd1d420fa67e7a8f26852196b80f6fa5"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "b0732421ae2999d558a7b70a11fa86a93738ca33f6f3ec343017796df9c47d9c"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "0bdcf1c5057873c78db71bee196ccf5ec846f6cf82f639b094668b3ba92e151f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/cofh-core.pw.toml"
hash = "2851d6afaaef7a6295ad252746fd4d200e96f7e85c24f11dca9be06ad221b41b"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "a2c5d820180d2610e5017e3f08957010e30cf05d50ee3180272dac6f969260cf"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "4063abe583282834b2f78e3b3e6b9ee4d231a680f74c020e405a4ef196f21ee4"
metafile = true

[[files]]
file = "mods/create-confectionery.pw.toml"
hash = "8845c6e549e63cef58e420a081b87e1db4230ea02efc835c74b8dab37e183148"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "87be52b8aaa9864eab1ec2df8c862cd01a084989b07c4cdbfaa21c57a9a778a6"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "c670ae9055f10dafb61fe340583c361f4c41ed45671c9440bae1f0696b47252a"
metafile = true

[[files]]
file = "mods/create-stuff-additions.pw.toml"
hash = "8d568223f61b027a5db4622d9d15dd8d00ccefe99e1cdcb6b62c0f0fae5c6f27"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "6f2228a2c8364467352de572c15c2b5dbdbd311307b76df0adf1545357c287c1"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "e6d1f36e9e0193fe410d136e0cda8a7f6dbbc809c0644f06a601bddf5b38a395"
metafile = true

[[files]]
file = "mods/cucumber.pw.toml"
hash = "20c32f8edb2bb36f9311d01857856948c249e7a22aca8868942c525678f3c3cc"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "9eefd607e0d54ec444e798ccdeede1a09a3939440bd1e11c11b84c07a5134be2"
metafile = true

[[files]]
file = "mods/cyclic.pw.toml"
hash = "f6855cec4d258048c432d0cfb2d5d68dd43433b697ef9c15958c85bbbd3bc840"
metafile = true

[[files]]
file = "mods/dynamic-torches.pw.toml"
hash = "69aaac3512cc2b6766260d707e28d56d9b53eb7a85532d9fe63052ebb046927c"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "78370ae52e87fdd72c5a988bed40674d1a7a9bc8a7d69e899f6a4fa91901925d"
metafile = true

[[files]]
file = "mods/farmers-delight-kacchi.pw.toml"
hash = "f35c9035e3ad37a0975aefeeec18370cc49e1b8ce17bccc4d4ca12f874d4f901"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f2ffb0d4c65fcb2a96878287a7119459b9d0637c395e5097d691416690d6563"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/flib.pw.toml"
hash = "ec9b48d07fdb821f60236006aeb33bb129abcee2ba044611a4758e31b2fa0bca"
metafile = true

[[files]]
file = "mods/ftb-chunks-compatibility-mod.pw.toml"
hash = "78d30294130d53db3b1de3bc1d97b8c55e32744ec26fc10a676ce0b7835e010d"
metafile = true

[[files]]
file = "mods/ftb-essentials.pw.toml"
hash = "8cf91dcad4590fed49069cdae47b211bdbee7da6e0c175ae802421ec6a961ae1"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "48e2fa3089beed20a23ff2d171259768b2080ab0ff196841a18eb93c38e1c8b2"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "64426fd63554594b3d2d2390cae5183309bb1ac2116db0baa77f1957d3eee4ac"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "1030e18f2e875dfdf39de82b823e1dfe6009f21f1aaad338137d3a90504e2f7e"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "71f185e62d546881244d4b5a213ebc3d2d6df14b0218c0e5dd6426fcb22cb55f"
metafile = true

[[files]]
file = "mods/grieflogger.pw.toml"
hash = "6406896463cb7c34d86cbe583b6fb2852c2306129d9770e403d817ac451a81a4"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "2e42b3a809ec9b027e23714e01c255fe5111a9d4cd58fad114dd0f2aa75c0d7e"
metafile = true

[[files]]
file = "mods/hexerei.pw.toml"
hash = "6b75e21a40b8dcfe80a1d29ce4b8b3168b07f1329688de128f49bafb802d169b"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "3aa4d2e503b7a4544868954aa8175335ee34714a8b44cc2a41cdbb833e271c31"
metafile = true

[[files]]
file = "mods/item-filters.pw.toml"
hash = "6f92d6a906fe5d960b53dc83e0060edfb2604f8deb4b38d25f7f66525966f7ad"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/jauml.pw.toml"
hash = "3898b08b8a39b960da43cb6785580d71d632829a5c7c89f0930bfe26ae3119ee"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b0441c2b5bb6ff680d97eac28d95847f0d4dbee34d1d42d897997b500acd44ca"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "02977d28acd2089c39dbe5b65fd08e78094fb650b4afc810f757cb5cea1fbda8"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1678327ac50408273c1828b631929128d3fdfd54cda7b2e823ce9352495a68ff"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "046be11686a9f13ce9ec8f87ff3b75274b93df8dd431b3c0f9748c1011944e69"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "b6ed220c9069f60704dbfe19fd55c976ca56ada35bcb6918c4ad226cd842b99c"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "6aa6897a3227a41db128aef512ad6e6cf33e3c3b806973f94bf63a2eed69f4df"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "66bcfe786e6bbdee6f7ea0805ec3d2561b41285a5c77f1e465e80f4c2fd9200c"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "f8b4210300a8f2ce76a2329de37f2e671ac5dfeca17018528cadb333b019a814"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "ee387ba74c2c7e999d48071408abbd1ca322e70f36e79c590a150c9572d3a9cb"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "e4f414ece2ec81f6dd2dfb8c0176670a576b988f60c8b45a1f4b749b4d008c9d"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "f009a177c97f9d189e9131704095060364b8201c83bd9118d89a11d25a6d2655"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
hash = "5ca76dcdb8448783ed3bb933ee2cefd017406d946b1b5adf7550ba7bcffe0932"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "1191b45155fb0f23f5a3fe4b9170b73f52a1c9599de504fe922e4ea7e7e3c95f"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "660d02d6316790b8b661d995c8e30d20891db05a337dc4e5c9d805c73a8fa14f"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "8728882e97cd2c7ff8746d95598be7f15fcb392dc9a146319504e0119f052a8e"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "eb6a1c1455632c6ea1ab12259d7082a19400be018eae95e44150a9f8fed330eb"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "426fd37ec95797af16797632e70c63436ca12719c0adb16ffca931970a411ee2"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ade41e4315735aa9116a0222b332e03d3f8df6eea301764d40d0bdc40f5e8689"
metafile = true

[[files]]
file = "mods/modonomicon.pw.toml"
hash = "11a52fe3ca031baf3f9425b0ac98bc79c8818bc261ee8f59ee7d322193902658"
metafile = true

[[files]]
file = "mods/modular-routers.pw.toml"
hash = "38eff2e2ce05f4d0a2f0bd8b53e0c71b39900ed530dcda25df28b2a84bbb217d"
metafile = true

[[files]]
file = "mods/mystical-agriculture.pw.toml"
hash = "0620cfb754ae5841a4383fb1db40f48a83b0c4fb659dd9b8dfe5cd51282a1f4e"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "362ead0883974a7de4dd711a75ccfe71b2ceadf172211934e8cd6084977c0f49"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "e6de05ff93544874f2e8a8f6646def228e877aad97396d14e43b9996849a4eab"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "d948acee031db5a8190fe05f2f2434584e6a4323c4ced6be03d2de091a05f9ba"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "08d4de41ece4f7ae64bb003e8ecbab1f0d5bde8ef611bad63598d2ee11faa8a2"
metafile = true

[[files]]
file = "mods/pandalib.pw.toml"
hash = "4684da1c9486b17aa9029f441b8b573a738bd256f413c30279950d2c9e8fe34f"
metafile = true

[[files]]
file = "mods/pandas-falling-trees.pw.toml"
hash = "28b26418642839f65e37b042a599d0a4956d601219f5afe4e2de1dc0d42baba0"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "dec2bc011d4ca1d451aaa3eea477f13366bfb13beba0716018f47d9331a50d8e"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "045d582e2c534c5bb96d7336b4ae2cd12692c6de29b19ae5f1dbfd8759c03b03"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4ab869d8784f4ac318b5c92fa3d9e65f997352b8b57f34b409ca6f171637f0fe"
metafile = true

[[files]]
file = "mods/ponder.pw.toml"
hash = "283faf9566f71aad6e8fdb646bb7b42678c05b102acc2ce9e75fe1ec665ad378"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "442f784b7c8e3d3231e407a9af4530c16fff9c301a5f57144fb5d895c754ded9"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "d83c43aa5cd92ee3427f79fcf1d4e4ecf763972aa4a9ea6eac87d865c2fe955f"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "5b92406160d9ea8a61ddf111caaecb7f6283678e2c40b08b72dce3eeaf20dc96"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "b8c7497acbf4890b4609b6b20de7affdd3482fc99af975d9ff6b29c075e1d8a7"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "ab891d8deeedfbdc6af5c0dfd4aa5e6811c6ca16afd6064129c48f2d9546dde0"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "b97a311aeaf633716450ac7ac644d8cdbc4b9731840ad1a08f9957a80de586e1"
metafile = true

[[files]]
file = "mods/smartbrainlib.pw.toml"
hash = "bd231c766e25e2f3a5fbfa7e7b8ade2536fed16c3a5574dc30b212dc51a75044"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "1d2b910e56a0abafd1230b076b519d48277e42d567ae82fac7ab2cfba37f4556"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "d65422fbf9a4a3d9449cb79905593d442ff0213e1de77e875b5023010b6426bb"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "0be4976227df8e261fd362889bf8e85b93e224d1b1c3cd2a11b73a9de3b64083"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "ff765c8249ef581bc6eef2ab9304f519aeec2552dc7a57760b7cd88eadd2685d"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "1cf9cb3955b075664ea4fba13b47fe7160975740a28864983aebd53d39c1946e"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "94880f4c797bec65ef62b0334792a699d4b0db9c4841465785368d3cf62e89e2"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "14117b94c456598c9acece143c7a0da3cf56d13182d035a74a2da8a52dd19cbd"
metafile = true

[[files]]
file = "mods/the-one-probe.pw.toml"
hash = "6f61f95a26011b08a22c9b5efa41ce8508a3843e7edeb78769debb35a01a4809"
metafile = true

[[files]]
file = "mods/thermal-expansion.pw.toml"
hash = "21ef66049ba994e620e34e2fab8e99ca27ceef5882f76dbd6c31afed66de89c4"
metafile = true

[[files]]
file = "mods/thermal-foundation.pw.toml"
hash = "876d11fe425ab32015927d63b35fa99b0cc24623916b4ba1951958c8fde5aacd"
metafile = true

[[files]]
file = "mods/untiled-entities.pw.toml"
hash = "bfe9286fdf10305e5aae15c1afdfa90df6e117ab0a963cfa33a516db7e182fb5"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "50dfd8547f93d1bc8f31e1740f94e24aadf661cb2948587ac16a41404b10effd"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "dd9c8d955749815ea13a1e500711926fd631bab441ceda04994ac84d1cdd52a6"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "c610e4f3a315259f44c6c2ce05503e93c7525a43a21d13f0e0661062cb82bede"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "b43f507cffbcc7178b184fa63b2d74fc6b2b8103c4d299ec5633ccf1f5abdafb"
metafile = true

[[files]]
file = "resourcepacks/beansilo.pw.toml"
hash = "dcc8397f8ca9f10a7170cda85e21a50f34bb94dde8d716d2614375b74f841d46"
metafile = true

[[files]]
file = "resourcepacks/better-nether.pw.toml"
hash = "6341b8f60b7e1bc4f778e5077255e621819a48bc7324c2f2f43ae7ceac04b0ba"
metafile = true
