name = "Thunder"
author = "https://github.com/rooneyj9005"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85aff83caed6f8988b477e0b1b4925bb48d99568c21ac897713222e71eb03a1c"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
